plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdkVersion 34
    buildToolsVersion "34.0.0"
    ndkVersion "21.3.6528147"

    defaultConfig {
        applicationId "com.thierry.android_surface_view_with_vulkan"
        minSdkVersion 28
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    // https://flutter.dev/docs/development/platform-integration/c-interop
    externalNativeBuild {
        // Encapsulates your CMake build configurations.
        cmake {
            version "3.10.2"
            // Provides a relative path to your CMake build script.
            path "./src/main/cpp/jni_vulkan/CMakeLists.txt"
        }
    }
    namespace 'com.thierry.android_surface_view_with_vulkan'
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.23"
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
