plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id("org.jetbrains.kotlin.plugin.compose") version "2.3.0"
}

android {
    compileSdkVersion 36
    buildToolsVersion "34.0.0"
    ndkVersion "21.3.6528147"

    defaultConfig {
        applicationId "com.thierry.android_surface_view_with_vulkan"
        minSdkVersion 28
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    // https://flutter.dev/docs/development/platform-integration/c-interop
    externalNativeBuild {
        // Encapsulates your CMake build configurations.
        cmake {
            version "3.10.2"
            // Provides a relative path to your CMake build script.
            path "./src/main/cpp/jni_vulkan/CMakeLists.txt"
        }
    }
    namespace 'com.thierry.android_surface_view_with_vulkan'

    buildFeatures {
        compose true
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.3.0"
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    def composeBom = platform('androidx.compose:compose-bom:2025.12.00')
    implementation composeBom
    androidTestImplementation composeBom

    // Choose one of the following:
    // Material Design 3
    implementation 'androidx.compose.material3:material3'

    // Optional - Add window size utils
    implementation 'androidx.compose.material3.adaptive:adaptive'

    // Optional - Integration with activities
    implementation 'androidx.activity:activity-compose:1.11.0'
    // Optional - Integration with ViewModels
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.5'
}
